_target_: lightning.pytorch.Trainer

accelerator: gpu
devices: auto
strategy: ddp

log_every_n_steps: 10
min_epochs: ???
max_epochs: ???
num_sanity_val_steps: 2
overfit_batches: 0.0
precision: 16
detect_anomaly: false
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
val_check_interval: 1.0
